### ISSUE TITLE
Not letting me host.

### ISSUE THREAD

**Issue by lkajdfklj** [cognetwork-dev/Cog-Dispenser#2]
this is still not letting me host it even when I make the secrets and fill out the .env file can you help me as soon as possible?

**Comment by MYSTERYS-ARE-FUN** [comment]
Could you send the error message and I’ll help you solve the problem asap

**Comment by Nebelung-Dev** [comment]
Your better off using https://github.com/titaniumnetwork-dev/Proxy-Dispenser
